language: cpp
os: linux
dist: xenial
sudo: enabled
python:
  - "3.7.1"

cache:
    directories:
      - /home/travis/build/Mrucznik/Mrucznik-RP-2.5/dependencies
      - /home/travis/.samp

branches:
  only:
  - master
  - development
  - hotfixy
  - mrucznik
  - creative
  - Sandal
  - donsimeone
  - system_grup

addons:
  apt:
    packages:
    - libc6:i386
    - libncurses5:i386
    - libstdc++6:i386

before_install:
- openssl aes-256-cbc -K $encrypted_774d02843e4b_key -iv $encrypted_774d02843e4b_iv
  -in id_rsa.enc -out id_rsa -d
- pyenv shell 3.7.1

install:
  - pip3 install chardet
  - sudo dpkg -i CI_scripts/sampctl_1.8.39_linux_amd64.deb # sampctl installation
  - sudo dpkg --add-architecture i386
  - sudo apt update && sudo apt install -y g++-multilib

script:
- chmod +x CI_scripts/*
- python3 CI_scripts/check_encoding.py gamemodes
- sampctl package ensure 
- sampctl package build 

before_deploy:
- echo "Before deploy"
- git config --local user.name "Mrucznik"
- git config --local user.email "mrucznix@gmail.com"
- export MRP_VERSION=$(grep -oP '\#define\ \VERSION \"\K(.+)(?=\")' gamemodes/VERSION.pwn)
- git tag "$MRP_VERSION-${TRAVIS_BUILD_NUMBER}"

deploy:
- provider: script
  script: CI_scripts/sftp_deploy.sh 5.133.9.55 2255 samp /home/samp/samp03/gamemodes
    gamemodes/Mrucznik-RP.amx
  skip_cleanup: true
  on:
    repo: Mrucznik/Mrucznik-RP-2.5
    all_branches: true
    condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^development|hotfixy|panpecet-new|creative|donsimeone|mrucznik|Sandal|system_([a-zA-z0-9]+)$
- provider: releases
  api_key:
    secure: SVD7s021RVq630lrOpaA9vDQLzXCvCid7LFNdz13J/xOgWkR+8mL9Ea0UwqsqEtOdkdx4IC8ltbU9jgxt5ZEEh/vQ5Euamp1Zrx9witn6dcS5B0ndQd4Ipjq+vq8Z2WFOYGbulBF4lQo5ZzZ17tDd2HJLBdG5iALIjEYeFvAdqba9Q1qLwQ8kBESoZrdr5i+0FWpZNHvsFeqXHKu4E+GI60Kv1wDT8YUMN/FBvVghkAyAfwTKzllt72lxqL+fZ6aDSIUARXF1r9afy6n4plZsBCzYvkQA1mvF2o0a16dZKml6ZSDaL/L39VKCa3gF63Zbl/YOMLwj6mUJkAf87siQsSa1ykv83ByyiOVxI8r+zgIa7Qt628HifUd+2Dq3RREB9tTvuhtJMIHBDDgmJCITmHLyRuyaD5M+L1xsa8vAGS9rCxeY6U5Gk/oY92O1Qd2QJC4zGBnAzUwlFuXLbGDx/X2PeL19jj+zO3h1ps7+vLQn/vKaQDuBdAvBkifcIJ5JHylrC5mBh329evf5EzTSC4t/2gWymcj5U4vZqY8EeCBm1kMkcIw+WvSpRD/vCBoEF4qcql6y+XpupDZSX1UYJMU3Ern4FQ+Yo9HHPLfPdCIvbWsz7MVya6chyxM6KrFwVs5rK98l0z5SqoU3Vm87s9oBo2mGXw1RqP0JemrOOQ=
  file: gamemodes/Mrucznik-RP.amx
  skip_cleanup: true
  prerelease: false
  name: Mrucznik-RP $MRP_VERSION build ${TRAVIS_BUILD_NUMBER}
  on:
    repo: Mrucznik/Mrucznik-RP-2.5
    branch: master

notifications:
  slack:
    rooms:
      secure: M3Be+dfEaGIUOXs4Q5EZpJKASFRFztaPXHDixK4ENncLU08tOZmvh98q/WzCsEIVeIWcvBC5JZZ3A2TQ8ykeUCFPnYdZCHE1uWp7Y9WDuSMjUp7e2GOOx+s4bPvyuKwoVE1tW0Zmhu7kh2cdx8iNigx5jfw0DRTqG1gPZJ/k0cNX2YftbLb9dQzJhCzx2OmmHiUsb6BlnGjl9cKtZorcc7YXkrAmJJMdATq5emv6kZWsvvDqKdDY2SM4LUdM+MWXujCvCX7a1R3dca936VA9aXAHATnGetwQkFWDv1CKQPG+vZWVtswDtXss4n2h+Iuut7RRmLcvaOCV9Lk7YZbyiyl2GMoujzYeNl3PAaj9YXLlAsLPlztTiowhuv+oQ8P0xumlOb33N7bky5/ZqIzTmt43bLwg4aLWFEsq9k51jW6w4S7RBe0TJ/WF1h/m73Xu75pWEceooRGIVVMYXZxRzktB+ESNf7TiEHXCJM/O+Cw4ReGf5FYpLDX2T+ev838FxkSuncwfB0mOioQ2aUStho+ZeHdsOIGegYizpxkMBMmcn74ZUyU6L3YCl5cCU69lEIRoNQwOP2vuze8+MBcZ+3ZDJL9lk7Qt4Ub1r7elAo3KPyUPzoEi/oIkM1QXyb0uOdlyI/vBwvQGCXqJE7cFrwJ+mcPwD4g54Lc2qvZeZ/U=
    on_pull_requests: false
    on_failure: change
    on_success: always

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
